# Generated by Django 3.2 on 2021-05-13 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.FileField(null=True, upload_to='post_images')),
                ('post_text', models.CharField(max_length=50, null=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('is_blur_post', models.BooleanField(default=False)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts Details',
            },
        ),
        migrations.CreateModel(
            name='BluredPost',
            fields=[
                ('blur_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blur_post', models.FileField(default=None, null=True, upload_to=posts.models.get_upload_postblur_path)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blured Post Details',
            },
        ),
    ]
