# Generated by Django 3.2 on 2021-04-28 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.FileField(null=True, upload_to='post_images')),
                ('post_text', models.CharField(max_length=50, null=True)),
                ('posted_time', models.TimeField(default=datetime.datetime(2021, 4, 28, 9, 51, 7, 596180, tzinfo=utc), editable=False)),
                ('posted_date', models.DateField(default=datetime.date(2021, 4, 28), editable=False)),
                ('post_likes', models.IntegerField(default=0)),
                ('is_blur_post', models.BooleanField(default=False)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BluredPost',
            fields=[
                ('blur_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blur_post', models.FileField(default=None, null=True, upload_to=posts.models.get_upload_postblur_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
