# Generated by Django 3.2 on 2021-04-28 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bluredpost',
            options={'verbose_name_plural': 'Blured Post Details'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts Details'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='posted_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 28, 9, 57, 43, 936829, tzinfo=utc), editable=False),
        ),
    ]
