# Generated by Django 3.2 on 2021-04-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10)),
                ('loaction', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(upload_to='profile-pic')),
                ('face_learn', models.FileField(upload_to='s<function get_upload_path at 0x00000165980C3D30>')),
                ('is_shield_active', models.BooleanField(default=False, verbose_name='shield')),
                ('Blur_dp', models.BooleanField(default=False, verbose_name='blur profile pic')),
                ('is_online', models.BooleanField(default=False, verbose_name='online')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
