# Generated by Django 3.2 on 2021-04-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default=None, max_length=20, null=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('contact', models.CharField(default=None, max_length=10, null=True)),
                ('date_of_birth', models.DateField(default=None)),
                ('loaction', models.CharField(default=None, max_length=50, null=True)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('state', models.CharField(default=None, max_length=20, null=True)),
                ('country', models.CharField(default=None, max_length=20, null=True)),
                ('profile_pic', models.FileField(default=None, null=True, upload_to='profile-pic')),
                ('profile_pic_blur', models.FileField(default=None, null=True, upload_to='profile-pic-blur')),
                ('cover_pic', models.FileField(default=None, null=True, upload_to='cover-pic')),
                ('Blur_dp', models.BooleanField(default=False, verbose_name='blur profile pic')),
                ('is_online', models.BooleanField(default=False, verbose_name='online')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
