# Generated by Django 3.2 on 2021-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='face_learn',
            field=models.FileField(default=None, upload_to='s<function get_upload_path at 0x00000231A56C3D30>'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='loaction',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profile-pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
