# Generated by Django 3.2 on 2021-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210414_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Blur_dp',
            field=models.BooleanField(blank=True, default=False, verbose_name='blur profile pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='face_learn',
            field=models.FileField(blank=True, default=None, upload_to='s<function get_upload_path at 0x00000153635E3D30>'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_shield_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='shield'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='loaction',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.FileField(blank=True, default=None, upload_to='profile-pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
