# Generated by Django 3.2 on 2021-04-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210414_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Blur_dp',
            field=models.BooleanField(default=False, verbose_name='blur profile pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='face_learn',
            field=models.FileField(default=None, null=True, upload_to='s<function get_upload_path at 0x00000253B46F3D30>'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_shield_active',
            field=models.BooleanField(default=False, verbose_name='shield'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='loaction',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.FileField(default=None, null=True, upload_to='profile-pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
