# Generated by Django 3.2 on 2021-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210414_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cover_pic',
            field=models.FileField(default=None, null=True, upload_to='cover-pic'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='face_learn',
            field=models.FileField(default=None, null=True, upload_to='s<function get_upload_path at 0x000001DA2BFF9DC0>'),
        ),
    ]
