# Generated by Django 3.2 on 2021-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userdetails_face_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic_blur',
            field=models.FileField(default=None, null=True, upload_to='profile-pic-blur'),
        ),
    ]
