# Generated by Django 3.2 on 2021-04-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdetails_profile_pic_blur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_shield_active',
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=False, verbose_name='shield')),
                ('active', models.BooleanField(default=False, verbose_name='shield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetails')),
            ],
            options={
                'verbose_name_plural': 'Shield Details',
            },
        ),
    ]
