# Generated by Django 3.2 on 2021-04-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20210418_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shield',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='pending',
            field=models.BooleanField(default=False, verbose_name='pending'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
