# Generated by Django 3.2 on 2021-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210418_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='danger',
            field=models.BooleanField(default=False, verbose_name='danger'),
        ),
        migrations.AddField(
            model_name='shield',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='warning'),
        ),
    ]
