# Generated by Django 3.2 on 2021-04-18 14:07

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20210418_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facelearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_training', models.FileField(default=None, null=True, upload_to=accounts.models.get_upload_path)),
                ('number_of_images', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facelearn Details',
            },
        ),
    ]
