# Generated by Django 3.2 on 2021-04-24 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faceshield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facelearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_training', models.FileField(default=None, null=True, upload_to=faceshield.models.get_upload_path)),
                ('number_of_images', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facelearn Details',
            },
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=False, verbose_name='pending')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('danger', models.BooleanField(default=False, verbose_name='danger')),
                ('warning', models.BooleanField(default=False, verbose_name='warning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shield Details',
            },
        ),
        migrations.CreateModel(
            name='FaceShieldDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_fsd', models.CharField(default=None, max_length=20, null=True)),
                ('facelearn_fsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceshield.facelearn')),
                ('shield_fsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceshield.shield')),
                ('user_fsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userdetails_fsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetails')),
            ],
            options={
                'verbose_name_plural': 'Face Shield Details',
            },
        ),
    ]
