# Generated by Django 3.2 on 2021-04-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceshield', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceshielddetails',
            name='facelearn_fsd',
        ),
    ]
