# Generated by Django 3.2 on 2021-05-13 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faceshield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faceshield', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluredImages',
            fields=[
                ('blur_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('blur_image', models.FileField(default=None, null=True, upload_to=faceshield.models.get_upload_blur_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blured Images Details',
            },
        ),
    ]
