# Generated by Django 3.2 on 2021-05-13 11:11

from django.db import migrations, models
import faceshield.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceshield', '0003_facelearnupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='facelearnupload',
            name='display_upload',
            field=models.BooleanField(default=True, verbose_name='upload pic'),
        ),
        migrations.AlterField(
            model_name='facelearnupload',
            name='face_training_pic',
            field=models.FileField(default=None, null=True, upload_to=faceshield.models.get_upload_path),
        ),
    ]
