# Generated by Django 3.2 on 2021-04-25 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notfication_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default=None, max_length=50, null=True)),
                ('message', models.CharField(default=None, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
