# Generated by Django 3.2 on 2021-05-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('notifications', '0002_alter_notifications_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotifications',
            fields=[
                ('notfication_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default=None, max_length=50, null=True)),
                ('message', models.CharField(default=None, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
