# Generated by Django 3.2 on 2021-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_postnotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postnotifications',
            options={'verbose_name_plural': 'Post Notifications'},
        ),
    ]
